controller_manager:
  ros__parameters:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      state_publish_rate: 100.0  # Ensure this is a double
    
    pos_joint_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      state_publish_rate: 100.0  # Ensure this is a double
