planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  scene_topic: "/planning_scene"
  publish_planning_scene: true
  publish_geometry_updates: true
  publish_state_updates: true
  publish_transforms_updates: true

motion_planning_pipeline:
  pipeline: ompl
  start_state_max_bounds_error: 0.1
  trajectory_execution.allowed_execution_duration_scaling: 1.2
  trajectory_execution.allowed_goal_duration_margin: 0.5

robot_description_kinematics:
  arm:
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.1

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  controller_manager_name: /controller_manager  # <-- Ensure this is placed here

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - pos_joint_traj_controller  # <-- Main controller name

controller_manager:
  ros__parameters:
    controller_list:
      - name: pos_joint_traj_controller
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint
